-- Migration: Add main_cat_id to places
-- Execute this in Supabase SQL Editor

ALTER TABLE places ADD COLUMN IF NOT EXISTS main_cat_id TEXT;

-- Update existing policies if needed (usually not needed if policy is "true")


-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

-- CREATE TABLE public.ads_settings (
--   id uuid NOT NULL DEFAULT uuid_generate_v4(),
--   slot_id text NOT NULL UNIQUE,
--   slot_label text NOT NULL,
--   ad_code text,
--   is_active boolean DEFAULT false,
--   updated_at timestamp with time zone DEFAULT now(),
--   CONSTRAINT ads_settings_pkey PRIMARY KEY (id)
-- );
-- CREATE TABLE public.categories (
--   id text NOT NULL,
--   name_ar text NOT NULL,
--   name_en text,
--   icon text DEFAULT 'folder'::text,
--   created_at timestamp with time zone DEFAULT now(),
--   CONSTRAINT categories_pkey PRIMARY KEY (id)
-- );
-- CREATE TABLE public.places (
--   id uuid NOT NULL DEFAULT gen_random_uuid(),
--   name_ar text NOT NULL,
--   name_en text,
--   main_cat_id text,
--   sub_cat_id text,
--   address text,
--   desc_ar text,
--   desc_en text,
--   image_url text,
--   images ARRAY DEFAULT '{}'::text[],
--   is_active boolean DEFAULT true,
--   created_at timestamp with time zone DEFAULT now(),
--   map_url text,
--   phone text,
--   whatsapp text,
--   working_hours text,
--   is_featured boolean DEFAULT false,
--   is_trending boolean DEFAULT false,
--   is_urgent boolean DEFAULT false,
--   has_offer boolean DEFAULT false,
--   offer_text_ar text,
--   offer_text_en text,
--   CONSTRAINT places_pkey PRIMARY KEY (id),
--   CONSTRAINT places_main_cat_id_fkey FOREIGN KEY (main_cat_id) REFERENCES public.categories(id),
--   CONSTRAINT places_sub_cat_id_fkey FOREIGN KEY (sub_cat_id) REFERENCES public.subcategories(id)
-- );
-- CREATE TABLE public.subcategories (
--   id text NOT NULL,
--   main_cat_id text,
--   name_ar text NOT NULL,
--   name_en text,
--   created_at timestamp with time zone DEFAULT now(),
--   CONSTRAINT subcategories_pkey PRIMARY KEY (id),
--   CONSTRAINT subcategories_main_cat_id_fkey FOREIGN KEY (main_cat_id) REFERENCES public.categories(id)
-- );